source "https://rubygems.org"

gem 'activerecord', '5.2', :require => 'active_record'
gem 'sinatra'
gem 'sinatra-activerecord'
gem 'rake'
gem 'require_all'
gem 'sqlite3', '~>1.3.6'
gem 'shotgun'
gem 'thin'
gem 'pry'
gem 'tux'
gem 'bcrypt'
# gem 'httparty'
gem 'nokogiri'